'''

   © 2023 Western Australian Land Information Authority

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

'''
# Generated by Django 3.1 on 2020-11-10 00:11

from __future__ import unicode_literals

from django.db import migrations, models
import os
from shutil import copyfile
from datetime import datetime, date
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.core.files import File
from django.conf import settings
import os
#########################################################################
################################ STAFF ##################################
boya = {
    'site_type' : 'staff_range',
    'site_name' : 'Boya',
    'site_status': 'open',
    'site_address' : 'Victor Road, Darlington',
    'country' : 'Australia',
    'state' : 'WA',
    'locality': 'Boya',
    'no_of_pillars': '21',
    'operator' : 'Landgate',
    'site_access_plan' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/Staff Range/Australia/WA/Boya/Access/Boya Access Plan.pdf'),
    'site_booking_sheet' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/Staff Range/Australia/WA/Boya/Access/Boya Booking Sheet.pdf'),
}    

muncheng = {
    'site_type' : 'staff_lab',
    'site_name' : 'Geodetic Laboratory at Munich',
    'site_status': 'open',
    'site_address' : 'Technical University of Munich',
    'country' : 'Others',
    'state' : 'OTH',
    'locality': 'Others',
    'no_of_pillars': '',
    'operator' : 'Landgate',
    'site_access_plan' : '',
    'site_booking_sheet' : '',
}    
#########################################################################
################################ EDM ####################################
edm_sites = [{
    'site_type' : 'baseline',
    'site_name' : 'Curtin',
    'site_status': 'open',
    'site_address' : 'Kent Street',
    'country' : 'Australia',
    'state' : 'WA',
    'locality': 'Bentley',
    'no_of_pillars': 11,
    'operator' : 'Landgate',
    'site_access_plan' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/WA/Curtin/Curtin EDM Baseline Access Sketch.pdf'),
    'site_booking_sheet' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/WA/Curtin/Curtin_EDM_Booking_Sheet_2021.pdf')
},{
    'site_type' : 'baseline',
    'site_name' : 'Curtin 12 Pillar',
    'site_status': 'open',
    'site_address' : 'Kent Street',
    'country' : 'Australia',
    'state' : 'WA',
    'locality': 'Bentley',
    'no_of_pillars': 12,
    'operator' : 'Landgate',
    'site_access_plan' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/WA/Curtin/Curtin EDM Baseline Access Sketch.pdf'),
    'site_booking_sheet' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/WA/Curtin/Curtin_EDM_Booking_Sheet_2021.pdf')
},{
    'site_type' : 'baseline',
    'site_name' : 'Busselton',
    'site_status': 'open',
    'site_address' : 'Busselton Bypass Road',
    'country' : 'Australia',
    'state' : 'WA',
    'locality': 'Busselton-Vasse',
    'no_of_pillars': 6,
    'operator' : 'Landgate',
    'site_access_plan' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/WA/Busselton/Busselton EDM Baseline Access Sketch.pdf'),
    'site_booking_sheet' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/WA/Busselton/Busselton_EDM_Booking_Sheet_2021.pdf'),
},{
   'site_type' : 'baseline',
    'site_name' : 'Kalgoorlie',
    'site_status': 'open',
    'site_address' : 'Piccadilly Street',
    'country' : 'Australia',
    'state' : 'WA',
    'locality': 'Kalgoorlie-Boulder',
    'no_of_pillars': 8,
    'operator' : 'Landgate',
    'site_access_plan' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/WA/Kalgoorlie/Kalgoorlie EDM Baseline Access Sketch.pdf'),
    'site_booking_sheet' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/WA/Kalgoorlie/Kalgoorlie_EDM_Booking_Sheet_2021.pdf')
},{
   'site_type' : 'baseline',
    'site_name' : 'Mawson Lakes',
    'site_status': 'open',
    'site_address' : 'University of South Australia Mawson Lakes Campus',
    'country' : 'Australia',
    'state' : 'SA',
    'locality': 'Mawson Lakes',
    'no_of_pillars': 7,
    'operator' : 'Office of the Surveyor-General - SA',
    'site_access_plan' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/SA/Mawson Lakes/2024-09-03-Mawson_baseline_access_diagram.pdf'),
    #'site_booking_sheet' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/SA/Mawson Lakes/2024-09-03-Mawson_baseline_access_diagram.pdf')
},{
   'site_type' : 'baseline',
    'site_name' : 'QLD.CABO2',
    'site_status': 'open',
    'site_address' : 'Dances Road',
    'country' : 'Australia',
    'state' : 'QLD',
    'locality': 'Caboolture',
    'no_of_pillars': 7,
    'operator' : 'Department of Natural Resources & Mines, Manufacturing & Regional & Rural Development',
    'site_access_plan' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Caboolture/2024-11-14-caboolture-baseline-location-map.pdf'),
    #'site_booking_sheet' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Caboolture/2024-11-14-caboolture-baseline-location-map.pdf')
},{
   'site_type' : 'baseline',
    'site_name' : 'QLD.EURE1',
    'site_status': 'open',
    'site_address' : '698 Eureka Station Road',
    'country' : 'Australia',
    'state' : 'QLD',
    'locality': 'Eureka',
    'no_of_pillars': 7,
    'operator' : 'Department of Natural Resources & Mines, Manufacturing & Regional & Rural Development',
    'site_access_plan' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Eureka/blank.pdf'),
    #'site_booking_sheet' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Eureka/blank.pdf')
},{
   'site_type' : 'baseline',
    'site_name' : 'QLD.GOLD3',
    'site_status': 'open',
    'site_address' : 'Shelter Road',
    'country' : 'Australia',
    'state' : 'QLD',
    'locality': 'Coombabah',
    'no_of_pillars': 7,
    'operator' : 'Department of Natural Resources & Mines, Manufacturing & Regional & Rural Development',
    'site_access_plan' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Coombabah/2024-11-14-gold-coast-baseline-location-map.pdf'),
    #'site_booking_sheet' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Coombabah/2024-11-14-gold-coast-baseline-location-map.pdf')
},{
   'site_type' : 'baseline',
    'site_name' : 'QLD.GOON1',
    'site_status': 'open',
    'site_address' : 'Goonyella Riverside Mine Access Rd',
    'country' : 'Australia',
    'state' : 'QLD',
    'locality': 'Moranbah',
    'no_of_pillars': 7,
    'operator' : 'Department of Natural Resources & Mines, Manufacturing & Regional & Rural Development',
    'site_access_plan' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Moranbah/2024-11-14-goonyella-baseline-location-map.pdf'),
    #'site_booking_sheet' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Moranbah/2024-11-14-goonyella-baseline-location-map.pdf')
},{
   'site_type' : 'baseline',
    'site_name' : 'QLD.LEYB1',
    'site_status': 'open',
    'site_address' : '10km northeast of Leyburn',
    'country' : 'Australia',
    'state' : 'QLD',
    'locality': 'Leyburn',
    'no_of_pillars': 7,
    'operator' : 'Department of Natural Resources & Mines, Manufacturing & Regional & Rural Development',
    'site_access_plan' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Leyburn/2024-11-19-leyburn-baseline-location-map.pdf'),
    #'site_booking_sheet' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Leyburn/2024-11-19-leyburn-baseline-location-map.pdf')
},{
   'site_type' : 'baseline',
    'site_name' : 'QLD.MACK2',
    'site_status': 'open',
    'site_address' : 'Mackay Regional Botanic Gardens',
    'country' : 'Australia',
    'state' : 'QLD',
    'locality': 'Mackay',
    'no_of_pillars': 7,
    'operator' : 'Department of Natural Resources & Mines, Manufacturing & Regional & Rural Development',
    'site_access_plan' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Mackay/2024-11-19-mackay-baseline-location-map.pdf'),
    #'site_booking_sheet' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Mackay/2024-11-19-mackay-baseline-location-map.pdf')
},{
   'site_type' : 'baseline',
    'site_name' : 'QLD.MICA2',
    'site_status': 'open',
    'site_address' : '5km south of the Mount Isa',
    'country' : 'Australia',
    'state' : 'QLD',
    'locality': 'Mount Isa',
    'no_of_pillars': 7,
    'operator' : 'Department of Natural Resources & Mines, Manufacturing & Regional & Rural Development',
    'site_access_plan' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Mount Isa/2024-11-19-mica-creek-baseline-location-map.pdf'),
    #'site_booking_sheet' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Mount Isa/2024-11-19-mica-creek-baseline-location-map.pdf')
},{
   'site_type' : 'baseline',
    'site_name' : 'QLD.TOWN2',
    'site_status': 'open',
    'site_address' : 'This baseline is located adjacent to the high voltage power lines on the northern side and parallel',
    'country' : 'Australia',
    'state' : 'QLD',
    'locality': 'Townsville',
    'no_of_pillars': 7,
    'operator' : 'Department of Natural Resources & Mines, Manufacturing & Regional & Rural Development',
    'site_access_plan' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Townsville/2024-11-19-townsville-location-map.pdf'),
    #'site_booking_sheet' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Townsville/2024-11-19-townsville-location-map.pdf')
},{
   'site_type' : 'baseline',
    'site_name' : 'QLD.TUNG1',
    'site_status': 'open',
    'site_address' : 'Tungamull, along a disused railway line just east of Rockhampton',
    'country' : 'Australia',
    'state' : 'QLD',
    'locality': 'Tungamull',
    'no_of_pillars': 7,
    'operator' : 'Department of Natural Resources & Mines, Manufacturing & Regional & Rural Development',
    'site_access_plan' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Tungamull/2024-11-19-tungamull-baseline-location-map.pdf'),
    #'site_booking_sheet' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Tungamull/2024-11-19-tungamull-baseline-location-map.pdf')
},{
   'site_type' : 'baseline',
    'site_name' : 'QLD.WALK1',
    'site_status': 'open',
    'site_address' : 'Opposite side of the Kennedy Highway to the Walkamin Agricultural Research Station',
    'country' : 'Australia',
    'state' : 'QLD',
    'locality': 'Walkamin',
    'no_of_pillars': 7,
    'operator' : 'Department of Natural Resources & Mines, Manufacturing & Regional & Rural Development',
    'site_access_plan' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Walkamin/2024-11-19-walkamin-baseline-location-map.pdf'),
    #'site_booking_sheet' : os.path.join(settings.STATIC_ROOT, 'data/InitialData/EDM Baseline/Australia/QLD/Walkamin/2024-11-19-walkamin-baseline-location-map.pdf')
}]

site_types = (
        (None, '--- Select Type ---'),
        # ('edm_lab', 'EDM Calibration Laboratory'),
        ('baseline','EDM Calibration Baseline'),
        ('staff_lab', 'Staff Calibration Laboratory'),
        ('staff_range','Staff Calibration Range'),               
        )
site_statuses = (
        (None, '--- Select Status ---'),
        ('open', 'Open'),
        ('closed', 'Closed'),
    )        
#########################################################################
def get_upload_to_location(instance, filename):
    creation_date = date.today().strftime('%Y-%m-%d')
    return '%s/%s/%s/%s/%s' % ('CalibrationSite', instance.site_type.capitalize(), instance.state.statecode, instance.site_name, creation_date+'-'+ filename)

file_storage = FileSystemStorage(location=os.path.join(settings.MEDIA_ROOT, 'media')) #

def load_initial_data(apps, schema_editor):
    
    Company = apps.get_model("accounts", "Company")
    Country = apps.get_model("calibrationsites", "Country")
    State = apps.get_model("calibrationsites", "State")
    Locality = apps.get_model("calibrationsites", "Locality")
    CalibrationSite = apps.get_model('calibrationsites', 'CalibrationSite')
    
    
    boya_site, created = CalibrationSite.objects.get_or_create(
        site_type = boya['site_type'],
        site_name = boya['site_name'],
        site_status = boya['site_status'],
        site_address = boya['site_address'],
        country = Country.objects.get(name = boya['country']),
        state = State.objects.get(statecode = boya['state']),
        locality = Locality.objects.get(name = boya['locality']),
        no_of_pillars = boya['no_of_pillars'],
        operator = Company.objects.get(company_name = boya['operator']),
        site_access_plan = File(open(boya['site_access_plan'], 'rb'), name = boya['site_access_plan'].split('/')[-1]),
        site_booking_sheet = File(open(boya['site_booking_sheet'], 'rb'), name = boya['site_booking_sheet'].split('/')[-1]),
    )
    
    munchen_site, created = CalibrationSite.objects.get_or_create(
        site_type = muncheng['site_type'],
        site_name = muncheng['site_name'],
        site_status = muncheng['site_status'],
        site_address = muncheng['site_address'],
        country = Country.objects.get(name = muncheng['country']),
        state = State.objects.get(statecode = muncheng['state']),
        locality = Locality.objects.get(name = muncheng['locality']),
        # no_of_pillars = muncheng['no_of_pillars'],
        operator = Company.objects.get(company_name = muncheng['operator']),
        # site_access = File(open(boya['site_access'], 'rb'), name = boya['site_access'].split('/')[-1]),
        # site_config = File(open(boya['site_config'], 'rb'), name = boya['site_config'].split('/')[-1]),
    )
    
    for edm_site in edm_sites:
        try:
            site, created = CalibrationSite.objects.get_or_create(
                site_type = edm_site['site_type'],
                site_name = edm_site['site_name'],
                site_status = edm_site['site_status'],
                site_address = edm_site['site_address'],
                country = Country.objects.get(name = edm_site['country']),
                state = State.objects.get(statecode = edm_site['state']),
                locality = Locality.objects.get(name = edm_site['locality']),
                no_of_pillars = edm_site['no_of_pillars'],
                operator = Company.objects.get(company_name = edm_site['operator']),
                site_access_plan = File(open(edm_site['site_access_plan'], 'rb'), name = edm_site['site_access_plan'].split('/')[-1]),
                site_booking_sheet = File(open(edm_site['site_booking_sheet'], 'rb'), name = edm_site['site_booking_sheet'].split('/')[-1]),
            )
        except KeyError:
            site, created = CalibrationSite.objects.get_or_create(
                site_type = edm_site['site_type'],
                site_name = edm_site['site_name'],
                site_status = edm_site['site_status'],
                site_address = edm_site['site_address'],
                country = Country.objects.get(name = edm_site['country']),
                state = State.objects.get(statecode = edm_site['state']),
                locality = Locality.objects.get(name = edm_site['locality']),
                no_of_pillars = edm_site['no_of_pillars'],
                operator = Company.objects.get(company_name = edm_site['operator']),
                site_access_plan = File(open(edm_site['site_access_plan'], 'rb'), name = edm_site['site_access_plan'].split('/')[-1]),
                # site_booking_sheet = File(open(edm_site['site_booking_sheet'], 'rb'), name = edm_site['site_booking_sheet'].split('/')[-1]),
            )

def reverse_func(apps, schema_editor):
    CalibrationSite = apps.get_model('calibrationsites', 'CalibrationSite')
    CalibrationSite.objects.filter(site_name = boya['site_name']).delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ('calibrationsites', '0002_auto_Create_Default_Locations'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func),
    ]

