# Generated by Django 3.1 on 2022-06-16 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrationsites', '0004_auto_Create_Default_Pillars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pillar',
            name='height',
            field=models.FloatField(blank=True, help_text='Enter the orthometic height, if known', null=True, validators=[django.core.validators.MinValueValidator(-30), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
