# Generated by Django 4.1.9 on 2025-01-15 03:55

import calibrationsites.models
import common_func.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calibrationsites", "0004_auto_Create_Default_Pillars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibrationsite",
            name="site_access_plan",
            field=models.FileField(
                help_text="Upload a pdf file showing an access to the location",
                null=True,
                upload_to=calibrationsites.models.get_upload_to_location,
                validators=[common_func.validators.validate_file_size],
                verbose_name="Access Plan",
            ),
        ),
        migrations.AlterField(
            model_name="calibrationsite",
            name="site_booking_sheet",
            field=models.FileField(
                help_text="Upload a pdf file containing the booking sheet",
                null=True,
                upload_to=calibrationsites.models.get_upload_to_location,
                validators=[common_func.validators.validate_file_size],
                verbose_name="Booking Sheet",
            ),
        ),
    ]
