# Generated by Django 4.1.9 on 2025-01-14 04:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calibrationsites", "0004_auto_Create_Default_Pillars"),
    ]

    operations = []
