# Generated by Django 4.1.9 on 2024-05-29 06:09

import calibrationsites.models
import common_func.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calibrationsites", "0004_auto_Create_Default_Pillars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibrationsite",
            name="site_access",
            field=models.FileField(
                help_text="Upload a pdf diagram showing an access to the location",
                null=True,
                upload_to=calibrationsites.models.get_upload_to_location,
                validators=[common_func.validators.validate_file_size],
                verbose_name="Access Summary",
            ),
        ),
        migrations.AlterField(
            model_name="calibrationsite",
            name="site_config",
            field=models.FileField(
                help_text="Upload a pdf diagram showing the location of pins or pillars",
                null=True,
                upload_to=calibrationsites.models.get_upload_to_location,
                validators=[common_func.validators.validate_file_size],
                verbose_name="Site Configuration",
            ),
        ),
    ]
