# Generated by Django 4.1.9 on 2025-01-30 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("calibrationsites", "0005_alter_calibrationsite_site_access_plan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pillar",
            name="site_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pillars",
                to="calibrationsites.calibrationsite",
                verbose_name="Site Name",
            ),
        ),
    ]
