# Generated by Django 4.1.9 on 2024-10-14 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline_calibration", "0002_auto_Create_Uncertainty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pillar_survey",
            name="variance",
        ),
        migrations.AddField(
            model_name="pillar_survey",
            name="experimental_std_dev",
            field=models.FloatField(
                blank=True,
                help_text="Experimental Standard Deviation of single observation (m) ISO 17123-4:2012 eq.14",
                null=True,
                verbose_name="Experimental Standard Deviation",
            ),
        ),
        migrations.AlterField(
            model_name="accreditation",
            name="LUM_constant",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(50.0),
                ],
                verbose_name="LUM constant",
            ),
        ),
        migrations.AlterField(
            model_name="accreditation",
            name="LUM_ppm",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(50.0),
                ],
                verbose_name="LUM ppm",
            ),
        ),
        migrations.AlterField(
            model_name="accreditation",
            name="valid_from_date",
            field=models.DateField(
                help_text="The date the period of appointment commences.",
                verbose_name="Valid From Date",
            ),
        ),
        migrations.AlterField(
            model_name="accreditation",
            name="valid_to_date",
            field=models.DateField(
                help_text="The date the period of appointment finishes.",
                verbose_name="Valid To Date",
            ),
        ),
    ]
