# Generated by Django 4.1.9 on 2024-05-29 06:09

import baseline_calibration.models
import common_func.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseline_calibration", "0002_auto_Create_Uncertainty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accreditation",
            name="certificate_upload",
            field=models.FileField(
                blank=True,
                max_length=1000,
                null=True,
                upload_to="accreditation_certificates/",
                validators=[common_func.validators.validate_file_size],
                verbose_name="Accreditation Certificate",
            ),
        ),
        migrations.AlterField(
            model_name="pillar_survey",
            name="fieldnotes_upload",
            field=models.FileField(
                blank=True,
                max_length=1000,
                null=True,
                upload_to=baseline_calibration.models.get_upload_to_location,
                validators=[common_func.validators.validate_file_size],
                verbose_name="Scanned fieldnotes",
            ),
        ),
    ]
