# Generated by Django 4.1.9 on 2025-02-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline_calibration", "0002_auto_Create_Uncertainty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uncertainty_budget_source",
            name="group",
            field=models.CharField(
                choices=[
                    ("01", "EDM scale factor"),
                    ("02", "EDMI measurement"),
                    ("03", "EDM LS zero offset"),
                    ("04", "Temperature"),
                    ("05", "Pressure"),
                    ("06", "Humidity"),
                    ("07", "Certified distances"),
                    ("08", "EDMI calibration"),
                    ("09", "Centring"),
                    ("10", "Heights"),
                    ("11", "Offsets"),
                ],
                help_text="Grouping of uncertainty source",
                max_length=3,
            ),
        ),
    ]
