# Generated by Django 4.1.9 on 2025-03-04 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline_calibration", "0003_alter_uncertainty_budget_source_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uncertainty_budget",
            name="std_dev_of_zero_adjustment",
            field=models.DecimalField(
                decimal_places=5,
                default=0.00029,
                help_text="Standard deviation applied to set of observations when all measured distances in set of observations are ezactly the same. (m)",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(5e-05)],
            ),
        ),
    ]
