# Generated by Django 4.1.9 on 2025-03-17 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "baseline_calibration",
            "0004_alter_uncertainty_budget_std_dev_of_zero_adjustment",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="accreditation",
            name="accredited_type",
            field=models.CharField(
                choices=[("B", "Baseline Calibration"), ("E", "EDMI Calibration")],
                default="B",
                help_text="The physical quantity that the authority is accredited to calibrate.",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="uncertainty_budget",
            name="std_dev_of_zero_adjustment",
            field=models.DecimalField(
                decimal_places=5,
                default=0.00029,
                help_text="Standard deviation applied to set of observations when all measured distances in set of observations are exactly the same. (m)",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(5e-05)],
            ),
        ),
        migrations.AlterUniqueTogether(
            name='accreditation',
            unique_together={('accredited_type', 'accredited_company', 'valid_from_date', 'valid_to_date')},
        ),
    ]
