# Generated by Django 3.1 on 2022-08-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0004_calibrated_baseline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calibrated_Baseline',
            new_name='Calibrated_BaselineA',
        ),
    ]
