# Generated by Django 3.1 on 2022-08-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0005_auto_20220801_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calibrated_BaselineA',
        ),
    ]
