# Generated by Django 3.1 on 2022-08-01 07:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0006_delete_calibrated_baselinea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibrated_Baseline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_point_correction', models.FloatField(help_text='If: Instrument Correction (m) = 1.00000013.L + 0.0003, Zero Point Correction = 0.0003m', validators=[django.core.validators.MinValueValidator(-0.1), django.core.validators.MaxValueValidator(0.1)])),
                ('zpc_uncertainty', models.FloatField(help_text='Uncertainty of the zero point correction (m) at 95% Confidence Level', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.1)], verbose_name='zero point correction uncertainty')),
                ('variance', models.FloatField(help_text='Variance of least squares adjustment of the calibration')),
                ('degrees_of_freedom', models.IntegerField(help_text='Degrees of freedom of calibration', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('pillar_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseline_calibration.pillar_survey')),
            ],
            options={
                'ordering': ['pillar_survey__baseline', '-pillar_survey__survey_date'],
            },
        ),
    ]
