# Generated by Django 3.1 on 2022-08-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0007_calibrated_baseline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calibrated_Baseline',
        ),
    ]
