# Generated by Django 3.1 on 2022-08-04 06:44

import baseline_calibration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0009_auto_20220802_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pillar_survey',
            name='fieldnotes_upload',
            field=models.FileField(blank=True, null=True, upload_to=baseline_calibration.models.get_upload_to_location, verbose_name='Scanned fieldnotes'),
        ),
    ]
