# Generated by Django 4.0.6 on 2022-08-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0010_auto_20220804_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='certified_distance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='edm_observation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='level_observation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pillar_survey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='std_deviation_matrix',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='uncertainty_budget',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='uncertainty_budget_source',
            name='group',
            field=models.CharField(choices=[('01', 'EDM scale factor'), ('02', 'EDMI measurement'), ('03', 'EDM LS zero offset'), ('04', 'Temperature'), ('05', 'Pressure'), ('06', 'Humidity'), ('07', 'LS fit unc fixed term'), ('08', 'LS fit unc proportional term'), ('09', 'Centring'), ('10', 'Heights'), ('11', 'Offsets')], help_text='Grouping of uncertainty source', max_length=3),
        ),
        migrations.AlterField(
            model_name='uncertainty_budget_source',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
