# Generated by Django 3.1 on 2023-01-10 03:31

import calibrationguide.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calibrationsites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_type', models.CharField(choices=[(None, '--- Select Type ---'), ('Site Calibration', (('baseline', 'EDM Baselines'), ('range', 'Staff Calibration Ranges'))), ('Instrument Calibration', (('edmi', 'Electronic Distance Measurements'), ('staff', 'Barcoded Staves')))], max_length=24, null=True, verbose_name='Calibration Type')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to=calibrationguide.models.get_upload_to_thumbnail, verbose_name='Thumbnail')),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Published on')),
                ('mod_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calibrationsites.calibrationsite', verbose_name='Calibration Site')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_type', models.CharField(choices=[(None, '--- Select Type ---'), ('tbaseline', 'EDM Baselines'), ('tedmi', 'Electronic Distance Measurements'), ('trange', 'Staff Calibration Range'), ('tstaff', 'Barcoded Staves')], max_length=24, null=True, verbose_name='Type')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to=calibrationguide.models.get_upload_thumbnail_to_manual, verbose_name='Thumbnail')),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Published on')),
                ('mod_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManualImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(blank=True, null=True, upload_to=calibrationguide.models.get_upload_images_to_manual)),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibrationguide.technicalmanual')),
            ],
        ),
        migrations.CreateModel(
            name='InstructionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(blank=True, null=True, upload_to=calibrationguide.models.get_upload_to_images)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibrationguide.calibrationinstruction')),
            ],
        ),
    ]
