'''

   © 2023 Western Australian Land Information Authority

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

'''
# Generated by Django 3.1 on 2020-11-10 00:11

from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings
import os
import csv

        
calibrationguides = [
    {'title' : 'EDM Baseline Calibration Instruction', 
     'thumbnail': 'CalibrationInstruction/Curtin/baseline/EDM Calibration Instruction/thumbnail_total_station.png',
     'content': os.path.join(settings.MEDIA_ROOT, 'InitialData/Calibration Guides/EDM Baseline Calibration Guide.html'),
     'site_name':'Curtin',
     'calibration_type':'baseline'
    },
    {'title' : 'EDMI Calibration Instruction', 
     'thumbnail': 'CalibrationInstruction/Curtin/edmi/EDMI Calibration Instruction/thumbnail_Picture2.124842.png',
     'content': os.path.join(settings.MEDIA_ROOT, 'InitialData/Calibration Guides/EDMI Calibration Guide.html'),
    'site_name':'Curtin',
    'calibration_type':'edmi'
    },
    {'title' : 'Range Calibration at Boya', 
     'thumbnail': 'CalibrationInstruction/Boya/range/Range Calibration Instruction/thumbnail_Picture2.124842.png',
     'content': os.path.join(settings.MEDIA_ROOT, 'InitialData/Calibration Guides/Range Calibration at Boya Guide.html'),
    'site_name':'Boya',
    'calibration_type':'range'
    },
    {'title' : 'Staff Calibration at Boya', 
     'thumbnail': 'CalibrationInstruction/Boya/range/Staff Calibration at Boya/thumbnail_Staff_icon_Vs87ZDG.PNG',
     'content': os.path.join(settings.MEDIA_ROOT, 'InitialData/Calibration Guides/Staff Calibration at Boya Guide.html'),
    'site_name':'Boya',
    'calibration_type':'range'
    },
]

    
tech_manual = {'manual_type':'tbaseline',
               'title': 'Medjil Technical Manual',
               'content': os.path.join(settings.MEDIA_ROOT, 'InitialData/Calibration Guides/Medjil Technical Manual.html'),
               'thumbnail':'TechnicalManual/tbaseline/Tech manual/thumbnail_Manual_icon_zomwENJ.PNG'
               }
                                                                                                                                                                                                                                                                                                              
#######################################################################
def load_initial_data(apps, schema_editor):
    CalibrationSite_obj = apps.get_model("calibrationsites", "CalibrationSite")
    instructions_obj = apps.get_model('calibrationguide', 'calibrationinstruction')
    technicalmanual_obj = apps.get_model('calibrationguide', 'technicalmanual')
    
    with open(tech_manual['content'], 'r', encoding='utf-8') as file:
        file_content = file.read()
        
    technicalmanual_obj.objects.get_or_create(
            manual_type  = tech_manual['manual_type'],
            title  = tech_manual['title'],
            content  = file_content,
            thumbnail  = tech_manual['thumbnail']
            )

    for guide in calibrationguides:
        with open(guide['content'], 'r', encoding='utf-8') as file:
            file_content = file.read()

        site_id_id = CalibrationSite_obj.objects.get(site_name = guide['site_name'])
        instructions_obj.objects.get_or_create(
            title  = guide['title'],
            thumbnail  = guide['thumbnail'],
            content  = file_content,
            site_id  = site_id_id,
            calibration_type  = guide['calibration_type'],
            )
    

class Migration(migrations.Migration):

    dependencies = [
        ('calibrationguide', '0001_initial'),
        ('calibrationsites', '0003_auto_Create_Default_Sites'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]

