# Generated by Django 4.1.9 on 2023-11-13 08:19

from django.db import migrations, models
import staffcalibration.models
from common_func.validators import validate_file_size

class Migration(migrations.Migration):

    dependencies = [
        ('staffcalibration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcalibrationrecord',
            name='field_book',
            field=models.FileField(blank=True, help_text='Upload the field book in pdf/jpg/tif format', null=True, max_length=1000, validators=[validate_file_size], upload_to=staffcalibration.models.get_upload_to_fieldbook, verbose_name='Field Book'),
        ),
    ]
