# Generated by Django 4.1.9 on 2023-12-13 06:09

import common_func.validators
from django.db import migrations, models
import staffcalibration.models


class Migration(migrations.Migration):
    dependencies = [
        ("staffcalibration", "0002_alter_staffcalibrationrecord_field_book"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffcalibrationrecord",
            options={
                "ordering": ["inst_staff", "calibration_date"],
                "verbose_name": "Barcode Staff Calibrations",
            },
        ),
        migrations.AlterField(
            model_name="staffcalibrationrecord",
            name="calibration_report",
            field=models.FileField(
                blank=True,
                help_text="Calibration report/certificate in pdf/jpg/tif format.",
                null=True,
                upload_to=staffcalibration.models.get_upload_to_calibreport,
                validators=[common_func.validators.validate_file_size],
                verbose_name="Calibration certificate",
            ),
        ),
        migrations.AlterField(
            model_name="staffcalibrationrecord",
            name="field_book",
            field=models.FileField(
                blank=True,
                help_text="Upload the field book in pdf/jpg/tif format",
                null=True,
                upload_to=staffcalibration.models.get_upload_to_fieldbook,
                validators=[common_func.validators.validate_file_size],
                verbose_name="Field Book",
            ),
        ),
        migrations.AlterField(
            model_name="staffcalibrationrecord",
            name="field_file",
            field=models.FileField(
                help_text="Upload the ASCII file generated by the level instrument",
                null=True,
                upload_to=staffcalibration.models.get_upload_to_fieldfile,
                validators=[common_func.validators.validate_file_size],
                verbose_name="Field Data",
            ),
        ),
    ]
