# Generated by Django 4.1.9 on 2024-05-10 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("calibrationsites", "0004_auto_Create_Default_Pillars"),
        ("staffcalibration", "0003_alter_staffcalibrationrecord_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffcalibrationrecord",
            name="inst_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Select level.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="instruments.digitallevel",
                verbose_name="Level Number",
            ),
        ),
        migrations.AlterField(
            model_name="staffcalibrationrecord",
            name="inst_staff",
            field=models.ForeignKey(
                help_text="Select staff.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="instruments.staff",
                verbose_name="Staff Number",
            ),
        ),
        migrations.AlterField(
            model_name="staffcalibrationrecord",
            name="site_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the staff calibration range. Please contact Landgate, if it does not exist.",
                limit_choices_to=models.Q(
                    ("site_type", "staff_range"),
                    ("site_type", "staff_lab"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="calibrationsites.calibrationsite",
                verbose_name="Calibration Site",
            ),
        ),
    ]
