# Generated by Django 4.1.9 on 2024-05-29 06:09

import common_func.validators
from django.db import migrations, models
import staffcalibration.models


class Migration(migrations.Migration):
    dependencies = [
        ("staffcalibration", "0004_alter_staffcalibrationrecord_inst_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffcalibrationrecord",
            name="field_book",
            field=models.FileField(
                blank=True,
                help_text="Upload the field book in pdf/jpg/tif format",
                max_length=1000,
                null=True,
                upload_to=staffcalibration.models.get_upload_to_fieldbook,
                validators=[common_func.validators.validate_file_size],
                verbose_name="Field Book",
            ),
        ),
        migrations.AlterField(
            model_name="staffcalibrationrecord",
            name="field_file",
            field=models.FileField(
                help_text="Upload the ASCII file generated by the level instrument",
                max_length=1000,
                null=True,
                upload_to=staffcalibration.models.get_upload_to_fieldfile,
                validators=[common_func.validators.validate_file_size],
                verbose_name="Field Data",
            ),
        ),
    ]