# Generated by Django 3.1 on 2022-02-23 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_auto_20220223_1004'),
        ('baseline_calibration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pillar_survey',
            name='barometer',
            field=models.ForeignKey(help_text='Barometer used for survey', limit_choices_to={'mets_specs__mets_model__inst_type': 'baro'}, on_delete=django.db.models.deletion.PROTECT, related_name='field_barometer', to='instruments.mets_inst'),
        ),
        migrations.AlterField(
            model_name='pillar_survey',
            name='hygrometer',
            field=models.ForeignKey(blank=True, help_text='Hygrometer, if used for survey', limit_choices_to={'mets_specs__mets_model__inst_type': 'hygro'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_hygrometer', to='instruments.mets_inst'),
        ),
        migrations.AlterField(
            model_name='pillar_survey',
            name='psychrometer',
            field=models.ForeignKey(blank=True, help_text='Psychrometer, if used for survey', limit_choices_to={'mets_specs__mets_model__inst_type': 'psy'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_psychrometer', to='instruments.mets_inst'),
        ),
        migrations.AlterField(
            model_name='pillar_survey',
            name='thermometer',
            field=models.ForeignKey(help_text='Thermometer used for survey', limit_choices_to={'mets_specs__mets_model__inst_type': 'thermo'}, on_delete=django.db.models.deletion.PROTECT, related_name='field_thermometer', to='instruments.mets_inst'),
        ),
        migrations.AlterField(
            model_name='uncertainty_budget_source',
            name='group',
            field=models.PositiveSmallIntegerField(choices=[('1', 'EDM scale factor'), ('2', 'EDM scale factor (temp. effect)'), ('3', 'EDM scale factor (drift over time)'), ('4', 'EDM zero offset'), ('5', 'Temperature unc'), ('6', 'Pressure unc'), ('7', 'Humidity unc'), ('8', 'LS fit unc fixed term'), ('9', 'LS fit unc proportional term'), ('10', 'Centring'), ('11', 'Heights'), ('12', 'Offsets'), ('13', 'Rounding')], help_text='Grouping of uncertainty source'),
        ),
    ]
