# Generated by Django 3.1 on 2022-02-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0002_auto_20220223_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uncertainty_budget_source',
            name='group',
            field=models.CharField(choices=[('1', 'EDM scale factor'), ('2', 'EDM scale factor (temp. effect)'), ('3', 'EDM scale factor (drift over time)'), ('4', 'EDM zero offset'), ('5', 'Temperature unc'), ('6', 'Pressure unc'), ('7', 'Humidity unc'), ('8', 'LS fit unc fixed term'), ('9', 'LS fit unc proportional term'), ('10', 'Centring'), ('11', 'Heights'), ('12', 'Offsets'), ('13', 'Rounding')], help_text='Grouping of uncertainty source', max_length=3),
        ),
    ]
