# Generated by Django 3.1 on 2022-02-28 01:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0003_auto_20220223_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uncertainty_budget_source',
            name='x_value',
        ),
        migrations.RemoveField(
            model_name='uncertainty_budget_source',
            name='x_value_k',
        ),
        migrations.AddField(
            model_name='uncertainty_budget_source',
            name='std_dev',
            field=models.FloatField(default=1, help_text='Standard deviation in terms of the units specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uncertainty_budget_source',
            name='uc95',
            field=models.FloatField(default=1, help_text='Uncertainty at 95% confidence in terms of the units specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uncertainty_budget_source',
            name='uc95_k',
            field=models.FloatField(default=2.0, help_text='The coverage factor for each input quantity. Typically 2.0 for a 95% confidence interval (normal distribution) or sqrt(3) for a rectangular distribution.', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='std_deviation_matrix',
            name='std_uncertainty',
            field=models.FloatField(help_text='One Sigma Standard deviation of certified distance - Type A uncertianty only from LSA', verbose_name='One Sigma Standard deviation'),
        ),
    ]
