# Generated by Django 3.1 on 2022-02-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0004_auto_20220228_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uncertainty_budget_source',
            name='std_dev',
            field=models.FloatField(help_text='Standard deviation in terms of the units specified', null=True),
        ),
        migrations.AlterField(
            model_name='uncertainty_budget_source',
            name='uc95',
            field=models.FloatField(help_text='Uncertainty at 95% confidence in terms of the units specified', null=True),
        ),
    ]
