# Generated by Django 3.1 on 2022-02-28 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0005_auto_20220228_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uncertainty_budget_source',
            name='uc95_k',
        ),
        migrations.AddField(
            model_name='uncertainty_budget_source',
            name='k',
            field=models.FloatField(default=2.0, help_text='The coverage factor for each input quantity. Typically 2.0 for a 95% confidence interval (normal distribution) or sqrt(3) for a rectangular distribution.', null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
