# Generated by Django 3.1 on 2022-03-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0006_auto_20220228_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uncertainty_budget_source',
            name='std_dev',
            field=models.FloatField(blank=True, help_text='Standard deviation in terms of the units specified', null=True),
        ),
        migrations.AlterField(
            model_name='uncertainty_budget_source',
            name='uc95',
            field=models.FloatField(blank=True, help_text='Uncertainty at 95% confidence in terms of the units specified', null=True),
        ),
    ]
