# Generated by Django 3.1 on 2022-03-21 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibrationsites', '0006_auto_20220321_2114'),
        ('baseline_calibration', '0007_auto_20220301_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certified_distance',
            name='from_pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certified_distance_from_pillar', to='calibrationsites.pillarb'),
        ),
        migrations.AlterField(
            model_name='certified_distance',
            name='to_pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certified_distance_to_pillar', to='calibrationsites.pillarb'),
        ),
        migrations.AlterField(
            model_name='edm_observation',
            name='from_pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_pillar', to='calibrationsites.pillarb'),
        ),
        migrations.AlterField(
            model_name='edm_observation',
            name='to_pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_pillar', to='calibrationsites.pillarb'),
        ),
        migrations.AlterField(
            model_name='level_observation',
            name='baseline_pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibrationsites.pillarb'),
        ),
        migrations.AlterField(
            model_name='std_deviation_matrix',
            name='from_pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distance_standard_deviation_from_pillar', to='calibrationsites.pillarb'),
        ),
        migrations.AlterField(
            model_name='std_deviation_matrix',
            name='to_pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distance_standard_deviation_to_pillar', to='calibrationsites.pillarb'),
        ),
    ]
