# Generated by Django 3.1 on 2022-03-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0008_auto_20220321_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pillar',
        ),
    ]
