# Generated by Django 3.1 on 2022-03-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0009_delete_pillar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EDM_Observation',
        ),
    ]
