# Generated by Django 3.1 on 2022-03-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0011_edm_observation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Std_Deviation_Matrix',
        ),
    ]
