# Generated by Django 3.1 on 2022-03-23 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibrationsites', '0008_auto_20220323_1223'),
        ('baseline_calibration', '0012_delete_std_deviation_matrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Std_Deviation_Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_uncertainty', models.FloatField(help_text='One Sigma Standard deviation of certified distance - Type A uncertianty only from LSA', verbose_name='One Sigma Standard deviation')),
                ('calibrated_baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseline_calibration.calibrated_baseline')),
                ('from_pillar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distance_standard_deviation_from_pillar', to='calibrationsites.pillar')),
                ('to_pillar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distance_standard_deviation_to_pillar', to='calibrationsites.pillar')),
            ],
        ),
    ]
