# Generated by Django 3.1 on 2022-03-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0013_std_deviation_matrix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certified_Distance',
        ),
    ]
