# Generated by Django 3.1 on 2022-03-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0015_certified_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uncertainty_budget_source',
            name='units',
            field=models.CharField(blank=True, choices=[('NA', 'Not applicable (NA)'), ('mm', 'millimetres (mm)'), ('m', 'metres (m)'), ('°C', 'Degrees Celcius (°C)'), ('hPa', 'hectopascals (hPa)'), ('mmHg', 'Millimetre of mercury (mmHg)'), ('%', 'percent (%)')], default='NA', help_text='Units of input quantity component', max_length=4, null=True),
        ),
    ]
