# Generated by Django 3.1 on 2022-04-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0016_auto_20220329_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='level_observation',
            name='rl_standard_deviation',
            field=models.DecimalField(decimal_places=4, default=0.002, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pillar_survey',
            name='baro_calib_applied',
            field=models.BooleanField(default=True, help_text='The barometer calibration correction has been applied prior to data import.', verbose_name='barometer calibration corrections applied'),
        ),
        migrations.AlterField(
            model_name='pillar_survey',
            name='edmi_calib_applied',
            field=models.BooleanField(default=False, help_text='The EDMI calibration correction has been applied prior to data import.', verbose_name='EDMI calibration corrections applied'),
        ),
        migrations.AlterField(
            model_name='pillar_survey',
            name='hygro_calib_applied',
            field=models.BooleanField(default=True, help_text='The hygrometer correction has been applied prior to data import.', verbose_name='Hygrometer calibration corrections applied'),
        ),
        migrations.AlterField(
            model_name='pillar_survey',
            name='mets_applied',
            field=models.BooleanField(default=True, help_text='Meterological corrections have been applied in the EDM instrument.', verbose_name='Atmospheric corrections applied'),
        ),
        migrations.AlterField(
            model_name='pillar_survey',
            name='staff_calib_applied',
            field=models.BooleanField(default=True, help_text='The staff calibration correction has been applied prior to data import.', verbose_name='staff calibration corrections applied'),
        ),
        migrations.AlterField(
            model_name='pillar_survey',
            name='thermo_calib_applied',
            field=models.BooleanField(default=True, help_text='The thermometer calibration correction has been applied prior to data import.', verbose_name='thermometer calibration corrections applied'),
        ),
    ]
