# Generated by Django 3.2.12 on 2022-05-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0018_auto_20220504_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uncertainty_budget_source',
            name='ab_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='B', help_text='Type A for a statistically derived component or Type B for any other derivation e.g. calibration report, manufacturers specification or an estimate based on experience.', max_length=1),
        ),
        migrations.AlterField(
            model_name='uncertainty_budget_source',
            name='distribution',
            field=models.CharField(choices=[('N', 'Normal'), ('R', 'Rectangular')], default='N', help_text='A normal distribution represents most physical situations. Notable exceptions include rounding and resolution of a digital instrument. These components would typically be rectangular in distribution (equal probability anywhere within the estimated uncertainty range).', max_length=1),
        ),
        migrations.AlterField(
            model_name='uncertainty_budget_source',
            name='group',
            field=models.CharField(choices=[('01', 'EDM scale factor'), ('02', 'EDMI measurement'), ('03', 'EDM zero offset'), ('04', 'Temperature'), ('05', 'Pressure'), ('06', 'Humidity'), ('07', 'LS fit unc fixed term'), ('08', 'LS fit unc proportional term'), ('09', 'Centring'), ('10', 'Heights'), ('11', 'Offsets')], help_text='Grouping of uncertainty source', max_length=3),
        ),
        migrations.AlterField(
            model_name='uncertainty_budget_source',
            name='units',
            field=models.CharField(blank=True, choices=[('ppm', 'Parts per million (ppm)'), ('%', 'percent (%)'), ('1:x', 'Ratio (1:x)'), ('mm', 'millimetres (mm)'), ('m', 'metres (m)'), ('°C', 'Degrees Celcius (°C)'), ('hPa', 'hectopascals (hPa)'), ('mmHg', 'Millimetre of mercury (mmHg)')], help_text='Units of input quantity component', max_length=4, null=True),
        ),
        migrations.AddConstraint(
            model_name='uncertainty_budget_source',
            constraint=models.CheckConstraint(check=models.Q(('std_dev__isnull', False), ('uc95__isnull', False), _connector='OR'), name='not_both_null'),
        ),
    ]
