# Generated by Django 3.1 on 2020-11-10 00:11

from __future__ import unicode_literals

from django.db import migrations, models
import csv
from datetime import datetime


def load_initial_data(apps, schema_editor):
	Company = apps.get_model("accounts", "Company")
	with open("assets/company/authority_names.csv", 'r') as f:
		reader = csv.reader(f)
		header = next(reader)

		companys = []
		for row in reader:
			company = Company.objects.create(company_abbrev = row[0], company_name = row[1])
			#print(company)

def reverse_func(apps, schema_editor):
	Company = apps.get_model("accounts", Company)

	Company.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(load_initial_data, reverse_func),
    ]
