# Generated by Django 3.1 on 2022-06-30 05:56

from django.db import migrations, models
import instruments.models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_auto_load_default_instruments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prism_inst',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=instruments.models.get_upload_to_prism_photos, verbose_name='Instrument photo'),
        ),
    ]
