# Generated by Django 4.0.6 on 2022-08-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_auto_load_landgate_instruments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mets_certificate',
            name='certificate_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/calibration_certificates/', verbose_name='Calibration Record'),
        ),
    ]
