# Generated by Django 4.1.9 on 2024-05-10 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0004_auto_recommended_specifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edm_inst",
            name="edm_specs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="instruments.edm_specification",
                verbose_name="EDM Specifications",
            ),
        ),
    ]
