# Generated by Django 4.1.9 on 2024-10-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0004_auto_recommended_specifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="iscalibrated",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Does it have a previous calibration record?",
                null=True,
                verbose_name="Is Calibrated",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="isreference",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Is this a reference Staff, e.g., invar staff used for calibrating the Staff Range?",
                null=True,
                verbose_name="Is Reference",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="staff_type",
            field=models.CharField(
                choices=[
                    (None, "Select one of the following"),
                    ("invar", "Invar"),
                    ("fiberglass", "Fibreglass"),
                    ("wood", "Wood"),
                    ("aluminium", "Aluminium"),
                    ("steel", "Steel"),
                    ("epoxy", "Carbon/epoxy"),
                    ("e_glass", "E-glass"),
                    ("s2_glass", "S2-glass"),
                ],
                max_length=10,
            ),
        ),
    ]
