# Generated by Django 4.1.9 on 2024-05-29 06:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0004_auto_recommended_specifications"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="digitallevel",
            options={
                "ordering": ["level_number", "level_make_name", "level_model_name"]
            },
        ),
        migrations.AlterModelOptions(
            name="edm_specification",
            options={"ordering": ["edm_make_name", "edm_model_name"]},
        ),
    ]
