# Generated by Django 4.1.9 on 2024-04-26 03:20

import common_func.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0004_auto_recommended_specifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edm_inst",
            name="comment",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                validators=[common_func.validators.validate_profanity],
            ),
        ),
        migrations.AlterField(
            model_name="edm_inst",
            name="edm_specs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="instruments.edm_specification",
                verbose_name="EDM Specifications",
            ),
        ),
    ]
