# Generated by Django 4.1.9 on 2024-08-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0004_auto_recommended_specifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="iscalibrated",
            field=models.BooleanField(
                blank=True,
                help_text="Does it have a previous calibration record?",
                null=True,
                verbose_name="Is Calibrated",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="isreference",
            field=models.BooleanField(
                blank=True,
                help_text="Is this a reference staff?",
                null=True,
                verbose_name="Is Reference",
            ),
        ),
    ]
