# Generated by Django 4.1.9 on 2024-10-14 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "instruments",
            "0005_alter_staff_iscalibrated_alter_staff_isreference_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="edm_specification",
            name="manu_unc_const",
            field=models.FloatField(
                help_text="Uncertainty = A mm ± B ppm, Uncertainty Constant = A",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                verbose_name="manufacturers uncertainty constant",
            ),
        ),
        migrations.AlterField(
            model_name="edm_specification",
            name="manu_unc_ppm",
            field=models.FloatField(
                help_text="Uncertainty = A mm ± B ppm, Uncertainty ppm = B",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                verbose_name="manufacturers parts per million uncertainty",
            ),
        ),
        migrations.AlterField(
            model_name="edmi_certificate",
            name="standard_deviation",
            field=models.FloatField(
                help_text="Experimental Standard Deviation of single observation (m) ISO 17123-4:2012 eq.14",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                verbose_name="Experimental Standard Deviation",
            ),
        ),
        migrations.AlterField(
            model_name="edmi_certificate",
            name="scale_correction_factor",
            field=models.FloatField(
                help_text="Note: scf as (A.x) = 1 + scf as (a.x) &#010Corrected Distance = scf.d + zpc, where scf is expressed as (A.x) &#010Instrument Correction  = scf.d + zpc, where scf is expressed as (a.x) &#010Instrument Correction  = scf.d.1e-6 + zpc, where scf is expressed as scf (ppm)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(2.0),
                ],
                verbose_name="Scale Correction Factor (scf)",
            ),
        ),
        migrations.AlterField(
            model_name="specifications_recommendations",
            name="manu_unc_const",
            field=models.FloatField(
                blank=True,
                help_text="Uncertainty = A mm ± B ppm, Uncertainty Constant = A",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                verbose_name="Manufacturers uncertainty constant",
            ),
        ),
        migrations.AlterField(
            model_name="specifications_recommendations",
            name="manu_unc_ppm",
            field=models.FloatField(
                blank=True,
                help_text="Uncertainty = A mm ± B ppm, Uncertainty ppm = B",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                verbose_name="Manufacturers ppm uncertainty",
            ),
        ),
    ]
