# Generated by Django 3.1 on 2022-07-21 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import instruments.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_calibration_report_notes'),
        ('instruments', '0005_auto_load_landgate_instruments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitallevel',
            name='level_model',
            field=models.ForeignKey(limit_choices_to={'inst_type__exact': 'level'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.instrumentmodel'),
        ),
        migrations.AlterField(
            model_name='edm_inst',
            name='edm_custodian',
            field=models.ForeignKey(blank=True, help_text='Name of instrument custodian', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='EDM Custodian'),
        ),
        migrations.AlterField(
            model_name='edm_inst',
            name='edm_number',
            field=models.CharField(help_text='Enter the instrument serial number / unique ID', max_length=15, verbose_name='EDM Number'),
        ),
        migrations.AlterField(
            model_name='edm_inst',
            name='edm_specs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.edm_specification', verbose_name='EDM Specification'),
        ),
        migrations.AlterField(
            model_name='edm_inst',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=instruments.models.get_upload_to_edm_photos, verbose_name='Instrument Photo'),
        ),
        migrations.AlterField(
            model_name='edm_specification',
            name='edm_model',
            field=models.ForeignKey(limit_choices_to={'inst_type__exact': 'edm'}, on_delete=django.db.models.deletion.PROTECT, to='instruments.instrumentmodel', verbose_name='EDM model'),
        ),
        migrations.AlterField(
            model_name='edm_specification',
            name='edm_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.company', verbose_name='EDM owner'),
        ),
        migrations.AlterField(
            model_name='edm_specification',
            name='edm_type',
            field=models.CharField(choices=[('ph', 'Phase'), ('pu', 'Pulse')], default='ph', help_text='Instrument measurement type', max_length=2, verbose_name='EDM type'),
        ),
        migrations.AlterField(
            model_name='instrumentmodel',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.instrumentmake'),
        ),
        migrations.AlterField(
            model_name='prism_inst',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=instruments.models.get_upload_to_prism_photos, verbose_name='Instrument Photo'),
        ),
        migrations.AlterField(
            model_name='prism_inst',
            name='prism_custodian',
            field=models.ForeignKey(blank=True, help_text='Name of instrument custodian', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Prism Custodian'),
        ),
        migrations.AlterField(
            model_name='prism_inst',
            name='prism_number',
            field=models.CharField(help_text='Enter the instrument serial number / unique ID', max_length=15, verbose_name='Prism Number'),
        ),
        migrations.AlterField(
            model_name='prism_inst',
            name='prism_specs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.prism_specification', verbose_name='Prism Specification'),
        ),
        migrations.AlterField(
            model_name='prism_specification',
            name='prism_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='Prism Owner'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_model',
            field=models.ForeignKey(limit_choices_to={'inst_type__exact': 'staff'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruments.instrumentmodel'),
        ),
    ]
