# Generated by Django 3.1 on 2022-07-21 03:01

from django.db import migrations, models
import instruments.models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_auto_20220721_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mets_inst',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=instruments.models.get_upload_to_mets_photos, verbose_name='Instrument photo'),
        ),
    ]
