'''

   © 2023 Western Australian Land Information Authority

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

'''
# Generated by Django 3.1 on 2020-11-10 00:11

from __future__ import unicode_literals

from django.db import migrations

def load_initial_data(apps, schema_editor):
    Company = apps.get_model("accounts", "Company")

    company = Company.objects.create(
        company_abbrev = 'OTH', company_name = 'Others', company_secret_key='')
    company = Company.objects.create(
        company_abbrev = 'LG', company_name = 'Landgate')

def reverse_func(apps, schema_editor):
    Company = apps.get_model("accounts", "Company")

    Company.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func),
    ]
