# Generated by Django 4.1.9 on 2023-08-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_load_report_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibration_report_notes",
            name="note_type",
            field=models.CharField(
                choices=[("M", "Manditory"), ("C", "Company Specific")],
                help_text="Notes can be either company specific or appear on all users reports",
                max_length=1,
            ),
        ),
    ]
