# Generated by Django 4.1.9 on 2025-01-14 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_medjiltotpdevice_roles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={},
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(
                help_text="Enter the full name of State/Region, e.g., Western Australia",
                max_length=40,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="statecode",
            field=models.CharField(
                help_text="Enter State Code with a max. of three letters, e.g., WA",
                max_length=3,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]*$", "Only capital letters are allowed"
                    )
                ],
                verbose_name="State Code",
            ),
        ),
    ]
