# Generated by Django 4.1.9 on 2025-01-15 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calibrationsites", "0005_alter_calibrationsite_site_access_plan_and_more"),
        ("accounts", "0006_alter_location_options_alter_location_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calibration_report_notes",
            options={"ordering": ["verifying_authority", "company", "site", "pillar"]},
        ),
        migrations.RenameField(
            model_name="calibration_report_notes",
            old_name="report_type",
            new_name="calibration_type",
        ),
        migrations.RemoveField(
            model_name="calibration_report_notes",
            name="note_type",
        ),
        migrations.AddField(
            model_name="calibration_report_notes",
            name="who_created_note",
            field=models.ForeignKey(
                help_text="Used for filtering the endnotes home page",
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.company",
            ),
        ),
        migrations.AddField(
            model_name="calibration_report_notes",
            name="accreditation",
            field=models.ForeignKey(
                blank=True,
                help_text="Notes will be created on all reports related to this Verifying Authority",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accreditation_notes",
                to="accounts.company",
            ),
        ),
        migrations.AddField(
            model_name="calibration_report_notes",
            name="pillar",
            field=models.ForeignKey(
                blank=True,
                help_text="Notes will be created on all reports related to this Pillar",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pillar_notes",
                to="calibrationsites.pillar",
            ),
        ),
        migrations.AddField(
            model_name="calibration_report_notes",
            name="site",
            field=models.ForeignKey(
                blank=True,
                help_text="Notes will be created on all reports related to this Site",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="site_notes",
                to="calibrationsites.calibrationsite",
            ),
        ),
        migrations.AddField(
            model_name="calibration_report_notes",
            name="verifying_authority",
            field=models.ForeignKey(
                blank=True,
                help_text="Notes will be created on all reports related to this Verifying Authority",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verifying_authority_notes",
                to="accounts.company",
            ),
        ),
        migrations.AlterField(
            model_name="calibration_report_notes",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Notes will be created on all reports related to this Company",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_notes",
                to="accounts.company",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the ones that applies to you. Hold down “Control”, or “Command” on a Mac, to select more than one.",
                to="accounts.location",
            ),
        ),
    ]
