# Generated by Django 4.1.9 on 2025-01-22 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("baseline_calibration", "0002_changes_from_beta_testing"),
        ("accounts", "0008_load_report_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibration_report_notes",
            name="accreditation",
            field=models.ForeignKey(
                blank=True,
                help_text="Notes will be created on all reports related to this Verifying Authority",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accreditation_notes",
                to="baseline_calibration.accreditation",
            ),
        ),
    ]
