# Generated by Django 4.1.9 on 2023-12-13 06:09

import common_func.validators
from django.db import migrations, models
import rangecalibration.models


class Migration(migrations.Migration):
    dependencies = [
        ("rangecalibration", "0002_auto_load_range_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rangecalibrationrecord",
            options={
                "ordering": ["inst_staff", "calibration_date"],
                "verbose_name": "Staff Range Calibrations",
            },
        ),
        migrations.AlterField(
            model_name="rangecalibrationrecord",
            name="calibration_report",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=rangecalibration.models.get_upload_to_calibreport,
                validators=[common_func.validators.validate_file_size],
                verbose_name="Calibration Certificate/Report",
            ),
        ),
        migrations.AlterField(
            model_name="rangecalibrationrecord",
            name="field_book",
            field=models.FileField(
                help_text="Upload the field book in pdf/jpg/tif format",
                null=True,
                upload_to=rangecalibration.models.get_upload_to_fieldbook,
                validators=[common_func.validators.validate_file_size],
                verbose_name="Field Book",
            ),
        ),
        migrations.AlterField(
            model_name="rangecalibrationrecord",
            name="field_file",
            field=models.FileField(
                help_text="Upload the ASCII file generated by the level instrument",
                null=True,
                upload_to=rangecalibration.models.get_upload_to_fieldfile,
                validators=[common_func.validators.validate_file_size],
                verbose_name="Field Data",
            ),
        ),
    ]
