# Generated by Django 3.2.12 on 2022-08-08 07:47

from django.db import migrations, models
import django.db.models.deletion
import edm_calibration.models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline_calibration', '0001_initial'),
        ('calibrationsites', '0001_initial'),
        ('edm_calibration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uedm_observation',
            name='use_for_distance',
            field=models.BooleanField(default=True, help_text='This observation (will) / (will not) be used for determining the calibration of the edmi.', verbose_name='Use for surveying the certified distances'),
        ),
        migrations.AddField(
            model_name='upillar_survey',
            name='site',
            field=models.ForeignKey(default=2, help_text='Baseline certified distances', on_delete=django.db.models.deletion.PROTECT, to='calibrationsites.calibrationsite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upillar_survey',
            name='test_cyclic',
            field=models.BooleanField(default=True, help_text="Test Instrument For Cyclic Errors (Nb. Instrument Parameters Require 'Unit Lenght'", verbose_name='Test for cyclic errors'),
        ),
        migrations.AlterField(
            model_name='upillar_survey',
            name='calibrated_baseline',
            field=models.ForeignKey(help_text='Baseline certified distances', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseline_calibration.pillar_survey'),
        ),
        migrations.AlterField(
            model_name='upillar_survey',
            name='fieldnotes_upload',
            field=models.FileField(blank=True, null=True, upload_to=edm_calibration.models.get_upload_to_location, verbose_name='Scanned fieldnotes'),
        ),
    ]
