# Generated by Django 4.0.6 on 2023-02-10 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('calibrationsites', '0005_remove_pillar_height_alter_calibrationsite_id_and_more'),
        ('edm_calibration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucalibration_parameter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='uedm_observation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='upillar_survey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='upillar_survey',
            name='job_number',
            field=models.CharField(blank=True, help_text='Job reference eg., JN 20212216', max_length=25, null=True, verbose_name='Job Number/Reference'),
        ),
        migrations.AlterField(
            model_name='upillar_survey',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Baseline certified distances', null=True, on_delete=django.db.models.deletion.PROTECT, to='calibrationsites.calibrationsite'),
        ),
    ]
