# Generated by Django 4.1.9 on 2025-01-15 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edm_calibration", "0002_changes_from_beta_testing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uedm_observation",
            name="raw_slope_dist",
            field=models.DecimalField(
                decimal_places=25,
                max_digits=29,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1500),
                ],
                verbose_name="slope distance",
            ),
        ),
    ]
