# Generated by Django 4.1.9 on 2025-03-20 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("edm_calibration", "0003_alter_uedm_observation_raw_slope_dist"),
    ]

    operations = [
        migrations.AddField(
            model_name="upillarsurvey",
            name="apply_lum",
            field=models.BooleanField(
                default=False,
                help_text="The Least Uncertainty of Measurement specified in the company's accreditation is applied if a posteriori uncertainties are less than LUM.",
                verbose_name="Apply LUM to underestimated uncertainties",
            ),
        ),
        migrations.AddField(
            model_name="upillarsurvey",
            name="e_accreditation",
            field=models.ForeignKey(
                blank=True,
                help_text="Accreditaion and LUM for EDM Instrumentation calibration.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="baseline_calibration.accreditation",
            ),
        ),
    ]
