# Generated by Django 3.2.12 on 2022-08-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edm_calibration', '0003_auto_20220808_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='upillar_survey',
            name='auto_base_calibration',
            field=models.BooleanField(default=True),
        ),
    ]
