# Generated by Django 3.1 on 2022-10-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edm_calibration', '0005_alter_uedm_observation_id_alter_upillar_survey_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uedm_observation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='upillar_survey',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
