# Generated by Django 3.1 on 2022-10-04 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edm_calibration', '0006_auto_20221004_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='uCalibration_Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('zpc', 'zero point correction'), ('scf', 'scale correction factor'), ('1C', '1 - Cyclic'), ('2C', '2 - Cyclic'), ('3C', '3 - Cyclic'), ('4C', '4 - Cyclic')], max_length=3)),
                ('value', models.FloatField(verbose_name='parameter Value')),
                ('std_dev', models.FloatField(verbose_name='standard deviation of this parameter')),
                ('k', models.FloatField(verbose_name='covereage factor')),
                ('pillar_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edm_calibration.upillar_survey')),
            ],
            options={
                'ordering': ['pillar_survey', 'term'],
                'unique_together': {('pillar_survey', 'term')},
            },
        ),
    ]
