# Generated by Django 3.2.12 on 2022-10-11 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edm_calibration', '0007_ucalibration_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='uedm_observation',
            name='degrees_of_freedom',
            field=models.IntegerField(blank=True, help_text='Degrees of freedom of calibration', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='uedm_observation',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='uedm_observation',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='uedm_observation',
            name='variance',
            field=models.FloatField(blank=True, help_text='Variance of least squares adjustment of the calibration', null=True),
        ),
        migrations.AlterField(
            model_name='ucalibration_parameter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ucalibration_parameter',
            name='k',
            field=models.FloatField(verbose_name='coverage factor'),
        ),
        migrations.AlterField(
            model_name='uedm_observation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='upillar_survey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
