# Generated by Django 3.2.12 on 2022-10-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edm_calibration', '0009_auto_20221011_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ucalibration_parameter',
            old_name='std_dev',
            new_name='standard_deviation',
        ),
    ]
