# Generated by Django 3.2.12 on 2022-10-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edm_calibration', '0012_alter_upillar_survey_k'),
    ]

    operations = [
        migrations.AddField(
            model_name='upillar_survey',
            name='scalar',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='a-priori standard uncertainties are multiplied by the a-priori scalar', max_digits=6, verbose_name='a-priori scalar'),
        ),
    ]
