# Generated by Django 4.0.6 on 2022-10-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edm_calibration', '0013_upillar_survey_scalar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upillar_survey',
            name='test_cyclic',
            field=models.BooleanField(default=False, help_text="Test Instrument For Cyclic Errors (Nb. Instrument Parameters Require 'Unit Lenght'", verbose_name='Test for cyclic errors'),
        ),
    ]
