# Generated by Django 4.1.9 on 2025-02-07 03:50

import calibrationsitebooking.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0009_alter_calibration_report_notes_accreditation"),
        ("calibrationsites", "0006_alter_pillar_site_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalibrationSiteBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calibration_type",
                    models.CharField(
                        choices=[
                            (None, "--- Select Type ---"),
                            (
                                "Site Calibration",
                                (
                                    ("baseline", "EDM Baseline"),
                                    ("range", "Staff Range"),
                                ),
                            ),
                            (
                                "Instrument Calibration",
                                (
                                    ("edmi", "Electronic Distance Measurement"),
                                    ("staff", "Barcoded Staff"),
                                ),
                            ),
                        ],
                        max_length=24,
                        null=True,
                        verbose_name="Calibration Type",
                    ),
                ),
                (
                    "job_number",
                    models.CharField(
                        help_text="Enter a job number, e.g., JN20222511",
                        max_length=15,
                        verbose_name="Job Number",
                    ),
                ),
                (
                    "calibration_date",
                    models.DateField(
                        help_text="Date of calibration",
                        null=True,
                        validators=[calibrationsitebooking.models.validate_future_date],
                    ),
                ),
                (
                    "calibration_time",
                    models.CharField(
                        choices=[
                            (None, "--- Select Time ---"),
                            ("08:00", "8 AM - 12 PM"),
                            ("13:00", "1:00 PM - 5:00 PM"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.location",
                        verbose_name="Location",
                    ),
                ),
                (
                    "observer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the calibration site.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calibrationsites.calibrationsite",
                        verbose_name="Calibration Site",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-calibration_date",
                    "calibration_time",
                    "location",
                    "site_id",
                ],
                "unique_together": {
                    ("site_id", "calibration_date", "calibration_time")
                },
            },
        ),
    ]
